---
title: "Using ggiraph for interactive plot in report"
author: "Federico Tiberti"
date: '2022-04-23'
lastMod: '2022-04-23'
slug: ggiraph-interactive-plot
categories: R
tags:
- R Markdown
- plot
- regression
---

For those looking for an alternative to plotly to create vectorized/interactive graphics keeping ggplot syntax: [ggiraph](https://davidgohel.github.io/ggiraph/#:~:text=ggiraph%20is%20a%20tool%20that,when%20used%20in%20shiny%20applications.) seems to be the solution. Brief example below:


```{r, echo=FALSE, message=FALSE, warning=FALSE}

lapply(c("tidyverse", "WDI", "countrycode", "ggiraph", "ggflags"), require, character.only=T)

gdppc <- WDI::WDI(indicator = "NY.GDP.PCAP.PP.KD", start = 2019, end = 2019) %>% 
  setNames(c("code", "country", "gdppc", "year")) %>% 
  select(-year) %>% 
  mutate(code = tolower(code))

vino <- read_csv("wine-consumption-per-person.csv") %>% 
  setNames(c("country", "code", "year", "wine")) %>% 
  filter(year==2019) %>% 
  mutate(code = tolower(countrycode(tolower(code), origin="iso3c", destination = "iso2c"))) %>% 
  left_join(gdppc, by="code")


vino %>% 
  mutate(log_gdp = log(gdppc), 
         log_wine = log(wine)) %>% 
  ggplot(aes(x=log_gdp, y=wine)) +
 theme_classic() +
  geom_flag(aes(country=code), size=3) +
  labs(x="Log GDP per capita, PPP, 2019", y="Wine consumption per capita, 2019") +
  theme(axis.text = element_text(face="bold", size=8), 
        axis.title = element_text(face= "bold", size=12), 
        plot.caption = element_text(size=6),
        plot.title = element_text(size=18, face="bold"))

```







```{r}
giraffe_points <- vino %>% 
  mutate(log_gdp = log(gdppc), 
         log_wine = log(wine)) %>% 
  ggplot(aes(x=log_gdp, y=wine)) +
 theme_classic() +
  geom_point_interactive(aes(tooltip = country.x, data_id = country.x)) +
  labs(x="Log GDP per capita, PPP, 2019", y="Wine consumption per capita, 2019") +
  theme(axis.text = element_text(face="bold", size=8), 
        axis.title = element_text(face= "bold", size=12), 
        plot.caption = element_text(size=6),
        plot.title = element_text(size=18, face="bold"))

girafe(ggobj = giraffe_points)
  
```


