---
title: "Using rayshader for 3D plots in R"
author: "Federico Tiberti"
date: '2022-05-05'
slug: rayshader-plot
categories: R
image:
  caption: ''
  focal_point: ''
  preview_only: yes
tags:
- R Markdown
- 3d plot
- rayshader
---

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
lapply(c("tidyverse", "janitor", "sf", "rayshader", "colorspace", "rgl"), require, character.only=T)
knitr::knit_hooks$set(webgl = hook_webgl)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
radios <- read_sf("https://cdn.buenosaires.gob.ar/datosabiertos/datasets/informacion-censal-por-radio/informacion-censal-por-radio-2010.csv") %>% 
  clean_names() %>%
  mutate(across(c(comuna, fraccion, radio, total_pob, t_varon, t_mujer, t_vivienda, v_particul, v_colectiv, t_hogar, h_con_nbi, 
        h_sin_nbi, id), as.numeric)) %>% 
 mutate(area = as.numeric(st_area(geometry)), 
         densidad = total_pob/area)

graph <-  radios %>% ggplot() +
  geom_sf(aes(fill=densidad), size=0.04, show.legend = FALSE) +
  scale_fill_continuous_sequential(palette="Reds 3") +
  coord_sf(datum=NA) + theme_minimal() +
  theme(axis.text.x = element_blank(),
        axis.text.y =   element_blank(),
        axis.ticks = element_blank()) 


```

Rayshader comes with a set of native functions to make 3D plots/maps. The function plot_gg() renders in 3D a ggplot object, projecting in third dimension the fill or color aesthetic. Example: population density by census track in the City of Buenos Aires (zoom in!):

```{r, webgl=TRUE}

plot_gg(graph, multicore = TRUE, width = 3 ,height=2, scale=250, fov = 70, zoom=0.3)

```





